GET http://localhost:5125/api/v1/customers?pageNumber=1&pageSize=1&searchQuery=Ghadah&sortBy=lastname&sortOrder=desc

###

POST http://localhost:5125/api/v1/customers 
Content-Type: application/json

{
  "FirstName": "Safaa",
  "LastName": "Alo",
  "Email": "Safaa@example.com",
  "Password": "securePassword1422",
  "Phone": "1234567000"
}

###
Get http://localhost:5125/api/v1/customers/2ac866ba-534e-4319-ac15-eaa46cf42d7d
###
Put http://localhost:5125/api/v1/customers/2ac866ba-534e-4319-ac15-eaa46cf42d7d
Content-Type: application/json

{
  "lastName": "Deef Allah",
  "phone": "1234567890"
}

###
Delete http://localhost:5125/api/v1/customers/f3fba3fa-2422-4959-a9f3-b5e00260deb2

###
Get http://localhost:5125/api/v1/addresses?pageNumber=1&pageSize=6&sortBy=state&sortOrder=desc
###
POST http://localhost:5125/api/v1/addresses 
Content-Type: application/json

{
  "AddressName": "Ida Aalbergin222",
  "StreetNumber": "1234",
  "StreetName": "Maple Avenue",
  "City": "Springfield",
  "State": "Illinois",
  "CustomerId": "2ac866ba-534e-4319-ac15-eaa46cf42d7d"
}

###

Get http://localhost:5125/api/v1/addresses/2a9ac9dc-5e19-4421-b8eb-197579f1e6af

###
Put http://localhost:5125/api/v1/addresses/2a9ac9dc-5e19-4421-b8eb-197579f1e6af
Content-Type: application/json

{
  "addressName": "alazizyah22"
}
###

DELETE  http://localhost:5125/api/v1/addresses/a2decf9f-9799-435a-a4c0-46cd002d99dd

###

Get http://localhost:5125/api/v1/payments?pageNumber=1&pageSize=3&searchQuery=111111111111111199911

###

Post http://localhost:5125/api/v1/payments
Content-Type: application/json

{
    "paymentMethod": "Cash",  
    "cardNumber": "111111111111111199911",  
    "totalPrice":  222,
    "CustomerId": "2ac866ba-534e-4319-ac15-eaa46cf42d7d"
  
}

###

Get http://localhost:5125/api/v1/payments/bf5d20a0-9d83-4feb-965f-542c7a0206f6

###
Put http://localhost:5125/api/v1/payments/bf5d20a0-9d83-4feb-965f-542c7a0206f6
Content-Type: application/json

{
  "paymentMethod": "ApplePay"
}

###

DELETE  http://localhost:5125/api/v1/payments/bf5d20a0-9d83-4feb-965f-542c7a0206f6
