###
GET http://localhost:5125/api/v1/users
###
GET http://localhost:5125/api/v1/users?pageNumber=1&pageSize=4&sortBy=lastname&sortOrder=desc

###

POST http://localhost:5125/api/v1/users 
Content-Type: application/json

{
  "FirstName": "Norah",
  "LastName": "Alp",
  "Email": "Norah@example.com",
  "Password": "securePassword1444",
  "Phone": "1234567333",
  "IsAdmin": false
}

###
Get http://localhost:5125/api/v1/users/459d7de7-2d6d-4eba-95eb-34104f12ba88
###
Put http://localhost:5125/api/v1/users/459d7de7-2d6d-4eba-95eb-34104f12ba88
Content-Type: application/json

{
  "lastName": "Deef Allah",
  "phone": "1234567890"
}

###
Delete http://localhost:5125/api/v1/users/459d7de7-2d6d-4eba-95eb-34104f12ba88

###
Get http://localhost:5125/api/v1/addresses
###
Get http://localhost:5125/api/v1/addresses?pageNumber=1&pageSize=6&sortBy=state&sortOrder=desc
###
POST http://localhost:5125/api/v1/addresses 
Content-Type: application/json

{
  "AddressName": "Alazizyah",
  "StreetNumber": "1234",
  "StreetName": "Alwaleed",
  "City": "Madinah",
  "State": "Saudi",
  "UserId": "bd0dd1fe-d8ab-4826-99dd-10459d6cf66b"
}

###

Get http://localhost:5125/api/v1/addresses/2a9ac9dc-5e19-4421-b8eb-197579f1e6af

###
Put http://localhost:5125/api/v1/addresses/2a9ac9dc-5e19-4421-b8eb-197579f1e6af
Content-Type: application/json

{
  "addressName": "alazizyah22"
}
###

DELETE  http://localhost:5125/api/v1/addresses/a2decf9f-9799-435a-a4c0-46cd002d99dd

###

Get http://localhost:5125/api/v1/payments?pageNumber=1&pageSize=3&searchQuery=111111111111111199911

###

Post http://localhost:5125/api/v1/payments
Content-Type: application/json

{
    "paymentMethod": "Cash",  
    "cardNumber": "111111111111111199911",  
    "totalPrice":  222,
    "UserId": "2ac866ba-534e-4319-ac15-eaa46cf42d7d"
  
}

###

Get http://localhost:5125/api/v1/payments/bf5d20a0-9d83-4feb-965f-542c7a0206f6

###
Put http://localhost:5125/api/v1/payments/bf5d20a0-9d83-4feb-965f-542c7a0206f6
Content-Type: application/json

{
  "paymentMethod": "ApplePay"
}

###

DELETE  http://localhost:5125/api/v1/payments/bf5d20a0-9d83-4feb-965f-542c7a0206f6
